---
- name: Create paths
  hosts: consul_instances
  tasks:
    - name: create optconsul
      ansible.builtin.file:
        path: /usr/bin/consul
        mode: 777
    - name: create hcl path
      ansible.builtin.file:
        path: /etc/consul.d
        mode: 777
    - name: create consulservice path
      ansible.builtin.file:
        path: /etc/systemd/system/
        mode: 777

- name: Download files
  hosts: consul_instances
  tasks: 
    - name: Download consul  
      ansible.builtin.copy:
        src: consul
        dest: /usr/bin/consul
        mode: 777
    - name: Download hclfile
      ansible.builtin.copy:
        src: consul.hcl
        dest: /etc/consul.d/consul.hcl
        mode: 777
    - name: Download consulservice
      ansible.builtin.copy:
        src: consul.service
        dest: /etc/systemd/system/consul.service
        mode: 777



#- name: Install Nginx
#hosts: 192.168.0.4
#become: true
#become_user: root
#roles:
#  - ansible-role-nginx
